sudo: required
dist: trusty
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
- sudo apt-get update -qq
- gem install bundler
install:
- bundle
language: ruby
cache: bundler
notifications:
  slack:
    secure: A/rqZkIsuFGcnw1o0CSowzEC883yxcF6uYVg1FY6FC50hUXhvRFsTmHIq3MWyiEnhj/4/1hSoIWaNAkBpn410iWttyZdWl7z1IZnL2ElqaEuyStEEBWonRSdKwBaDQ2/zvtBD5P2mFs7WtmggemqSK6ctz2CnQEudhZQROAUDdwKGiqKNnyb7enyHBJDOfTMlecJpIRh3NTz34A9XKm67YZpUwqOn9tRi/c9NDt1vMlzOvSxUY1sfx3i6QVWts1RxoluH9gnQcXAAjplIui4qf41rL4GvLl9IpJA/05m0zTUGGNu64ydp5PBQ6rJIYId5picRCJG04eh3kJAeHcDLDLSQA/SqAKV5BnRMK1Wsv7S8VyYONL6sCRKf7WEuJcjGOWppEYcxtw4uFd2zejc0E56Wg/8WZjtj4lSLE1pkpF/K8/vtcVop66G4MiMkrrGzSSYgrKPTo9N6nIhyvEjSLyz2gcx5AE6RiMWVNGftsomhpFcT9fkcyRiyRg8gW6nLkEaKLaTjE4dxrrtYy56QEc4k/s33AQ2/RzpMATZineybR1I195q8G5jReihVKsggJMd0C2EAhns6sgEjTbteE2dzIMKeE6nBRCmZyrRfXiUo8L5x6UutzjIGUVwWjGS+t03DByn78z0XDCk6wA7+imoq6N29LqeU0pkiga2pd0=
rvm:
- 2.3.1
before_script:
- bin/setup
script:
- npm install -g bower
- npm install
- bundle exec rake assets:clobber && bundle exec rake assets:precompile
- xvfb-run -a bin/ci
deploy:
  provider: heroku
  app:
    dev: coposition-staging
  api_key:
    secure: b3zqr4Cr2I1MqWVDfYigZM8eTtRXwIN82v38/M822aN0+DW/PsLjWdHzI27MpRzSMx2JGe/kDeaOU4NpjoSq840cmqCQEPIefoaGLYULL0oTcGdMBBP9sL0MEBj6JFYxpdRSj7gJDmRzKBNErO1wLdKjQxuZiHh8W+IBqePZ+DLnEawXOidjQZIuXBxW31DKI5Qh7Dj4xgkRqrkq6GPkQMxzhQwgd4/oPxXnWZq4+Pbhi2bFEzxM7nGGfcaPgLVCC4qi1IaSyoY7YThpzC9gN5ntkkL5mXJggow7SGbuvEqwnzoZVfPdOf/DKXgEOQQInqbTV0j3viTliFMKWWxkXDF6b0iy0m0m87jqDlLwMw4Py3ugRh/Yiqkb66B9hfbS/dDpCKWsGxrnfjahkxvp+l1WAo0D+syPal/f8yxSuWQFVaPizVVP8/ZmtBhykT1sg65ZTuCZH+oTDcYjPOsTEC9VmuS84yyzOX7bE7k2n3LLkkttTEBj2FAEWfHeE/e7w55rKhSY0I/CwZHNP/zspH7crGIRdeRB8obmu9pfS7195syUCIGcunisOSKiJ4xVVcbe0QaJxIeUiPRFQcVyvA4+p5hkMmM6TUlyd+x/5NQdnFPvjBSZWV0ClsEI7D3Zg7KRQtVmYylm28WOYgeyxxkj/T+QW3kBnOlq4o5FjOQ=
  run: rake db:migrate
addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - libqt4-dev
    - libqtwebkit-dev
    - xvfb
  code_climate:
    repo_token:
      secure: bdK/4NHC+zT68KBsIESldomWL+fwyDVAiPsgPdZAUiCm2cbP4RTL+tEc9ZMYvM1n2Lw/sbVZ79xwC2+YVgj86J71ra9+grb5KJabeKDStnlI9Q9n+XDSkHMjwwHecl/noZzMmMHyVDL4ts5wXLAWdQ5LlPApIchBurHFciD8Z6EOvz5elqCjA5ap7V1WhffqE5gCM38iy217BE6CFtiQskpWaHjzVHmrM0OPJrtDg3mtxcTmI8+QiySTA+5ETQCbv40iuOenQixkCIMU1Fy8+0PwaC4ZcJGiCYI7o79A6NiSry+zbgZhDrIieUpLMhecIipby7jg46qjUfTQWNVlHl9UBBhw8pkjbH2n91AD7GF6jhyl7yin4s5TY1ml1SeQZg31jFW+o3rTfwPvsnZ+T4IN8Ue/WXKJRg1QsEYkaXQIoN4M0CtTUIGrQcbcjYnpnmKdySqI10H5/QFAEfP3OAUD3plzD/IlIl2bh6ry8E7RmVYdB1/jCGjqWAoJbmhEc1EuCqXg0mSGVW5ljHweMFKRTew/TT1u03dTuxzt3NH+CzpIL4KpjfKC69tavrH2AQYreIq2vXt/NJZqj4i1ZIF29kPFAAYwOkmfA15zezkC0dw3yB5OJPUWK3P0682W3/g4XDWAgyvYMyNTCUyfBB0+kptg+oT4q6M+CJjMpLM=
env:
  global:
  - secure: wALNTSL1dmR32hcbg3eqP66+PojecOKnzRNCVdprR0N+noe3BPy4NqmKPgpM3UXQDcUtmRVB7bJCmJtd2zIBfsGL26LuILv3JemV7eeF5eiNGf6vvXsBHVLT2a8QoaEBJcJtKI1+R0BC3vp2cWTot2A46RXN70T+yM3pVfGKZAggY7XnIUYU60rr6XCIFqE20ibEWD06iMT/DE/euEOAw0CNJeipCp4/WxaJVp+N3qV+yy4LgPhTX9jM3wUm99MNrpFm6uutHlFZbv+ljV2tQcb4rrX79j6YkU9XJEV0MOBLvXxRE7lFfEVEJ708kgPv0xt7EQ7PcplrDkqe+ByUEro7HmfFEK9XTrHJiiMRzAV4F77Eo+rmqiC/HfsgSCR9PqmrulPtWG67hzxHoSxUzY2jU2KaVT3Hki/Dxxh90HCVBEr3XtTprztsHg9rsZcGzB/zgOzBcYBkQ3ldgjIun3VdRj0uXOVjHF4cbvJuz8oPVKHF5SUUD0iwNMKfQN15wiR9ErfOtPgPVbryuJ6f62VOj3MmzLv50R2srCFsnCqSLOtrjnVGbebqluZ442yWJ8n/kd2k2UyKrbIHFBwNdSA5J1Gbtl9je6Tr3HlHDAHA9RL/htVzCfNPTphiIr53UM9dZWijgcjWK/qqAdVUoB8DWCFjcOPpTzAXBCceMoQ=
  - secure: nlPXv03+m0/JfJp6olSxA7JP4BZSqtx+Rz1hFh8yPMRnD1UAW7G1IPpaJR+oDT9yKHSrqtVvFHC8L5ytfueh6/iP9pGqCqY6cbGcJiRUS3oJV0es1BkvQcKkfiqHjlZr6lmLfkNSGnQtNS+Z0dNVM9Bz7QAE+Gf3P8m/3WR88ZqCOekLjU3ZpbukiipzpAQ/uzx9wsar9NcKplentYTyDBLcf5rNk+ZgfObuS23zsJDyrJoMGmb4JvQfhYeeX181aapScc1EwoDVApZqWXR29BdIc8RV91MjpaZHTwWDUNzlwdbtuXAslDaaYu/3Ck5ldWPqKbthGbf0P0gurmNThqNahis1XBMfJY+bMgFExq/T2DBak8ov3q5jnI3MoKXqrsHzdxZPjGsPDg2eAzz2/ewZQ5+Rf/jTICTM5BZ86SthBMQNuTt/bvr4UI8XXmSn+LJeKkTsu2Y0GFWX0Rk+H5O1tAF22loMDISBcxyMIGYNDwaOq69xJLCZ7UidQoM8AXs6dOKlnoMbQYqVoim01E24oIz6u3oW4/Vv4SOc1KePyua83hrBdSxgWvBD+mjd7aMDdsSPHpgsw9iYqxy9foThxeULLPOGcpDUn4UKOcFrtJueMAJx6r3bSZYi2rK3Lo9mCMwxt5/keqKKJapr7FC1/X3CuS6cr+LLiISgZH8=
  - secure: pw7v/VPqPCFM40RhrsIbSYLB/WdyNIztathNOh2ptLb3os1cD3EqjBml3Y2stuH5RnpOxZmM9wjMb/LgQ9d7IJOgw0yj80dHu7zl1eio7mz3zRz4wc0omtvHQNiadLn4IcJig+ARY62WHc0UaquNVw0vsVhCXOLKuXAvYBZflTotBGiHi1tT1xki5h3lmXsm36E1DVjC3C0tNMwx+/S9qnyEHc8B1AH9Ll5eMxoAk9VoioWy6bJByn2x/GI42a1BPmXONHT63DO9x/sx6+JGKTbqLNyB581l3bp8/5O808xgE8xcqoBT10bzQxw/eaAl2quRoLT4pHc1FkxtPzRmTT3vYbyRuE/ytex0v5lrvJ0aMiASu6PKtlU3Ehigxk+8zWNNLSMq5uYI1BQoAIEP9YXMD7fm4kwp+BmEeqz1J1J27PlLV8gnnByOnZHZxGTLfdUxRt0oNm+wUFPIgULLumEih5y6dodrl9p4Mrgr28tatph8N/IOncgKcoWgJfbWKypDHx8F1uKMgLVJ3eTvGjtPDdjNsfcbum6g5n6yUw6mfFJlFWPhKQ1Y+cdgrLY/E0L+UxmC+Nl4iKvLCJpJp3jfByqxDyn8VgqrX7rU5jGNquSXKcmu9swkqM77HEB62vDD/jPjfLe27oI4ovF2e62ynmzRlykNSRq/kiiQAFg=
  - secure: kLxc9n2BlJlGg+92IlRa6Y0WNYPjItjFwiotUVdTmW7jvi8NW8KMMtMqZg+WoXSGP12nsELtTQvWqzb1rhonE8JbBkLpcxiOznEzYGJ9m12Szj6SlDTh6i6A6htOJcO8nKnTWliy6ZNjA2BSEvWaCXmLsMHLg3ezbKwrdFi428W4thux3S3q8lcSzyKOntN0J4R2rOjNsyA1C46lfY5mryoGkAsWWmLmH9AbEZvRrKH3tijCrV/LxcmNdt2NqZGBzOm0ulJh8qVI/jMlJWy6q5pQXtwS76cNsMBmIHf7g2O1Z8bqgsEICgqY93tUDQF2vnbRS6oKmgittrw+k/0oJFCA9TX9pkMsqpcfRji65CQQLPsPNmF07l6dRkgbeFN6scm6IxjQouve8JJKhzl/s3ksRQhz6P/EF+51N6z8zjrlqm4XC5YYYiCClQ0DMGDs/8Rb2INYuhyLVXs+mQjKfRRIabSuSnHBOW/pHMFVNYJyKPGbo9fP14zgglXr0+l9HomnAAejpMgQRGtNUzmErYxre8/BCHyfzWqgi26x/6Hh6WwPONrxCHrbLHY4BU5ICl1JgRFB59Yls1hxAEf8K3vZ7sPOuOj3bXieEViefJQFVPaVt1OGBiBkh28HMnEC6eupnlfqnnqF3FSGzRwGaPLomMHjXesXtyn4E+l8tqg=
