redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis

test: 
  adapter: async

benchmark: *redis

staging:
  <<: *redis
  url: <%= ENV["REDISTOGO_URL"] %>

production:
  <<: *redis
  url: <%= ENV["REDISTOGO_URL"] %>
